name: Lint

on:
  pull_request:
    branches:
      - "release*"
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    environment:
      name: reviewdog
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
      - run: npm ci
      - name: reviewdog / ESLint
        uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd # v1.33.2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          fail_level: "warning"
          eslint_flags: "src"
      - name: astro check
        run: npm run astro check
